In [109]:
import numpy as np

data = np.load(r"E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\interpolated_keypoints\kicking\kicking_1.npy")
print(data)

[[[[401.63113   54.89623 ]
   [389.3697    68.42823 ]
   [378.52612   68.47074 ]
   [375.7755    92.952354]
   [377.10104  117.43399 ]
   [400.2306    65.778145]
   [404.32022   87.537346]
   [407.02066  103.80222 ]
   [393.4218   114.65524 ]
   [385.30124  114.70355 ]
   [385.30685  148.72343 ]
   [360.79517  167.7368  ]
   [397.5961   113.37529 ]
   [398.9198   147.28839 ]
   [397.47516  178.54395 ]
   [397.60754   49.507057]
   [405.63077   49.484512]
   [390.70486   48.135   ]
   [168.10754   34.99607 ]
   [406.99692  185.38766 ]
   [407.03812  181.3214  ]
   [393.4482   178.66057 ]
   [363.47507  179.93315 ]
   [356.71927  177.26134 ]
   [355.39633  167.6681  ]]

  [[472.3135    69.81616 ]
   [487.25858   92.921394]
   [495.423     91.60752 ]
   [495.38712  114.705215]
   [154.12099   62.11058 ]
   [481.79      92.98503 ]
   [473.6343   124.269966]
   [461.4141   144.63283 ]
   [476.40137  145.9478  ]
   [483.17572  144.646   ]
   [472.22943  178.58562 ]
   [465.51306  208.5514  ]

In [90]:
data.size

5100

In [91]:
data.shape

(51, 2, 25, 2)

In [22]:
import numpy as np

# Assuming you have a NumPy array called 'keypoints' with zero values
# Replace 0 values with the worst value (minimal value other than 0) for each column
def replace_zero_values(keypoints):
    min_gt0 = np.ma.array(keypoints, mask=keypoints <= 0).min(0)
    keypoints = np.where(keypoints == 0, min_gt0, keypoints)
    return keypoints

# Example usage:
# Replace zeros in your numpy array 'my_keypoints' with actual values
my_keypoints = np.load(r"E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\keypoints_extracted_clean\hugging\hugging_1.npy")

print("original:", my_keypoints)

updated_keypoints = replace_zero_values(my_keypoints)
print("Updated:",  updated_keypoints)


original: [[[[257.52155   80.7037  ]
   [288.71732   86.17852 ]
   [299.66724   68.45229 ]
   ...
   [332.27112  220.76022 ]
   [337.67627  218.06148 ]
   [352.58618  227.5721  ]]

  [[265.66138   37.19807 ]
   [256.129     68.46548 ]
   [242.48601   80.753204]
   ...
   [292.82584  211.2848  ]
   [294.18646  211.26816 ]
   [290.11154  209.91418 ]]]


 [[[256.19025   80.70704 ]
   [288.72235   86.16987 ]
   [299.65298   68.45481 ]
   ...
   [332.2614   220.7656  ]
   [336.34738  218.06377 ]
   [351.30573  227.56317 ]]

  [[265.66956   37.197945]
   [256.13672   67.118004]
   [242.47234   80.71379 ]
   ...
   [292.85464  211.27467 ]
   [294.1851   211.26717 ]
   [288.82202  209.89034 ]]]


 [[[254.81087   83.4656  ]
   [287.4291    88.883316]
   [299.66675   68.48757 ]
   ...
   [332.27426  220.75029 ]
   [337.6772   218.0384  ]
   [351.3177   227.53656 ]]

  [[268.3642    37.200523]
   [260.22092   63.05595 ]
   [243.83614   78.011795]
   ...
   [290.1463   209.90376 ]
   [292.80902  2

In [23]:
updated_keypoints.shape

(51, 2, 25, 2)

In [24]:
check_zeros = np.all(updated_keypoints == 0)

In [25]:
check_zeros

False

In [32]:
import os
import numpy as np

# Assuming you have a NumPy array called 'keypoints' with zero values
# Replace 0 values with the worst value (minimal value other than 0) for each column
def replace_zero_values(keypoints):
    min_gt0 = np.ma.array(keypoints, mask=keypoints <= 0).min(0)
    keypoints = np.where(keypoints == 0, min_gt0, keypoints)
    return keypoints

# Path to the main folder containing subfolders
main_folder = r"E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\keypoints_extracted_clean"

# List of subfolder names (class names)
class_names = ['hugging', 'kicking', 'punching', 'pointing', 'none-interaction', 'pushing']

# Loop through each class folder
for class_name in class_names:
    class_folder = os.path.join(main_folder, class_name)
    # Loop through each file in the class folder
    for file_name in os.listdir(class_folder):
        file_path = os.path.join(class_folder, file_name)
        if file_name.endswith('.npy'):
            keypoints = np.load(file_path)
            updated_keypoints = replace_zero_values(keypoints)
            # Save the updated keypoints back to the same file
            np.save(file_path, updated_keypoints)
            print(f"Updated keypoints saved to {file_path}")


Updated keypoints saved to E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\keypoints_extracted_clean\hugging\hugging_1.npy
Updated keypoints saved to E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\keypoints_extracted_clean\hugging\hugging_10.npy
Updated keypoints saved to E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\keypoints_extracted_clean\hugging\hugging_100.npy
Updated keypoints saved to E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\keypoints_extracted_clean\hugging\hugging_101.npy
Updated keypoints saved to E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\keypoints_extracted_clean\hugging\hugging_102.npy
Updated keypoints saved to E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\keypoints_extracted_clean\hugging\hugging_103.npy
Updated keypoints saved to E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\keypoints_extracted_clean\huggi

split data into train and test 70-30

In [110]:
import os
import numpy as np
from sklearn.model_selection import train_test_split

# Define the path to your main folder (keypoint)
main_folder = r"E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\interpolated_keypoints"

# Initialize lists to store data and labels
data = []
labels = []

# Iterate through each subfolder
for subfolder in os.listdir(main_folder):
    subfolder_path = os.path.join(main_folder, subfolder)
    if os.path.isdir(subfolder_path):
        # Load numpy files from each subfolder
        for file in os.listdir(subfolder_path):
            if file.endswith(".npy"):
                file_path = os.path.join(subfolder_path, file)
                keypoints = np.load(file_path)  # Load numpy data
                data.append(keypoints)
                labels.append(subfolder)  # Use subfolder name as label

# Convert lists to numpy arrays
data = np.array(data)
labels = np.array(labels)

# Split data into train and test sets with a 70-30 split
X_train, X_test, y_train, y_test = train_test_split(data, labels, test_size=0.3, random_state=42)

# Now you have X_train, y_train (70% of data), and X_test, y_test (30% of data)
print("Train data shape:", X_train.shape)
print("Y train shape:", y_train.shape)
print("Test data shape:", X_test.shape)
print("Y test shape:", y_test.shape)

output_folder = r"E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\split-data-interpolate"
os.makedirs(output_folder, exist_ok=True)
np.save(os.path.join(output_folder, "X_train.npy"), X_train)
np.save(os.path.join(output_folder, "y_train.npy"), y_train)
np.save(os.path.join(output_folder, "X_test.npy"), X_test)
np.save(os.path.join(output_folder, "y_test.npy"), y_test)

print("Data saved successfully in the 'split_data' folder!")


Train data shape: (462, 51, 2, 25, 2)
Y train shape: (462,)
Test data shape: (198, 51, 2, 25, 2)
Y test shape: (198,)
Data saved successfully in the 'split_data' folder!


In [32]:
import numpy as np

def calculate_distance(keypoints):
    num_keypoints = keypoints.shape[0]
    distances = np.zeros((num_keypoints, num_keypoints))
    
    for i in range(num_keypoints):
        for j in range(i+1, num_keypoints):
            if np.any(keypoints[i] != 0) and np.any(keypoints[j] != 0):  # Check if keypoints are detected
                distances[i][j] = np.linalg.norm(keypoints[i] - keypoints[j])
            else:
                distances[i][j] = np.nan  # If one of the keypoints is not detected, set distance to NaN
    
    return distances

keypoints = np.load(r"E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\keypoints_extracted_clean\pointing\pointing_5.npy")

distances = calculate_distance(keypoints)
print(distances)


[[  0.           7.8564496    7.83188438 ... 490.28466797 492.57272339
  492.45407104]
 [  0.           0.           3.18751359 ... 490.0980835  492.36734009
  492.24520874]
 [  0.           0.           0.         ... 490.36813354 492.64749146
  492.52536011]
 ...
 [  0.           0.           0.         ...   0.          15.40925026
   15.30821228]
 [  0.           0.           0.         ...   0.           0.
    2.62067127]
 [  0.           0.           0.         ...   0.           0.
    0.        ]]


pairwise keypoint for feature extract

In [35]:
import numpy as np

# Load the numpy file containing keypoints
keypoints_array = np.load(r"E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\keypoints_extracted_clean\pointing\pointing_5.npy")

# Function to calculate Euclidean distance between two keypoints
def euclidean_distance(keypoint1, keypoint2):
    return np.linalg.norm(keypoint1 - keypoint2)

# Function to calculate Euclidean distances between all pairs of keypoints in a frame
def pairwise_distances(frame_keypoints):
    num_keypoints = frame_keypoints.shape[0]
    distances = np.zeros((num_keypoints, num_keypoints))
    for i in range(num_keypoints):
        for j in range(num_keypoints):
            distances[i, j] = euclidean_distance(frame_keypoints[i], frame_keypoints[j])
    return distances

# Iterate through each frame in the keypoints array
for frame_keypoints in keypoints_array:
    # Calculate pairwise distances between keypoints in the current frame
    distances = pairwise_distances(frame_keypoints)
    print("Pairwise distances for frame:")
    print(distances)


Pairwise distances for frame:
[[  0.         848.30334473]
 [848.30334473   0.        ]]
Pairwise distances for frame:
[[  0.         847.44171143]
 [847.44171143   0.        ]]
Pairwise distances for frame:
[[  0.        848.2543335]
 [848.2543335   0.       ]]
Pairwise distances for frame:
[[  0.         846.73602295]
 [846.73602295   0.        ]]
Pairwise distances for frame:
[[  0.         846.34649658]
 [846.34649658   0.        ]]
Pairwise distances for frame:
[[  0.        846.0824585]
 [846.0824585   0.       ]]
Pairwise distances for frame:
[[  0.         846.14202881]
 [846.14202881   0.        ]]
Pairwise distances for frame:
[[   0.         1048.48913574]
 [1048.48913574    0.        ]]
Pairwise distances for frame:
[[   0.        1048.5592041]
 [1048.5592041    0.       ]]
Pairwise distances for frame:
[[  0.         953.49633789]
 [953.49633789   0.        ]]
Pairwise distances for frame:
[[  0.         953.37225342]
 [953.37225342   0.        ]]
Pairwise distances for fr

In [36]:
distances.shape

(2, 2)

In [60]:
import numpy as np

def replace_zeros_with_previous_frame_keypoints(keypoints_array):
    # Iterate through each frame
    for i in range(1, len(keypoints_array)):
        # Iterate through each keypoint in the current frame
        for j in range(len(keypoints_array[i])):
            # If the current keypoint is [0, 0], replace it with the corresponding keypoint from the previous frame
            if np.all(keypoints_array[i][j] == 0):
                keypoints_array[i][j] = keypoints_array[i-1][j]
            # If the current keypoint is detected, update the previous keypoint
            else:
                keypoints_array[i-1][j] = keypoints_array[i][j]
    return keypoints_array

# Test the function
keypoints_array = np.load(r"E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\keypoints_extracted_clean\hugging\hugging_3.npy")
updated_keypoints_array = replace_zeros_with_previous_frame_keypoints(keypoints_array)
print(updated_keypoints_array)



[[[[476.4016    67.125084]
   [460.0553    80.74109 ]
   [456.0212    82.12881 ]
   ...
   [480.456    211.20775 ]
   [472.32306  211.23827 ]
   [450.51846  197.65588 ]]

  [[504.88663   69.88059 ]
   [485.92227   87.52562 ]
   [483.1824    91.549484]
   ...
   [  0.         0.      ]
   [  0.         0.      ]
   [  0.         0.      ]]]


 [[[504.89526   69.836105]
   [488.61133   88.88934 ]
   [483.17184   91.566696]
   ...
   [480.4566   211.22343 ]
   [472.30084  211.23413 ]
   [  0.         0.      ]]

  [[483.19885   64.428154]
   [462.7715    80.66933 ]
   [462.7782    82.06549 ]
   ...
   [  0.         0.      ]
   [  0.         0.      ]
   [450.53033  197.64311 ]]]


 [[[483.1932    64.4345  ]
   [462.7719    80.665474]
   [462.7817    82.062454]
   ...
   [480.44943  211.21928 ]
   [472.29492  211.23134 ]
   [449.18997  196.30067 ]]

  [[504.894     69.83737 ]
   [488.60812   88.89584 ]
   [483.17105   91.571236]
   ...
   [  0.         0.      ]
   [  0.         0.      ]

In [53]:
import numpy as np

data = np.load(r"E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\keypoints_extracted_clean\hugging\hugging_3.npy")
print(data)

[[[[473.59958   63.07204 ]
   [454.65897   80.68791 ]
   [453.2567    82.09461 ]
   ...
   [480.47528  211.16708 ]
   [472.34073  211.20038 ]
   [451.88104  198.99092 ]]

  [[504.9652    69.84088 ]
   [485.9532    88.86648 ]
   [484.4985    91.536804]
   ...
   [  0.         0.      ]
   [  0.         0.      ]
   [  0.         0.      ]]]


 [[[476.4016    67.125084]
   [460.0553    80.74109 ]
   [456.0212    82.12881 ]
   ...
   [480.456    211.20775 ]
   [472.32306  211.23827 ]
   [450.51846  197.65588 ]]

  [[504.88663   69.88059 ]
   [485.92227   87.52562 ]
   [483.1824    91.549484]
   ...
   [  0.         0.      ]
   [  0.         0.      ]
   [  0.         0.      ]]]


 [[[504.89526   69.836105]
   [488.61133   88.88934 ]
   [483.17184   91.566696]
   ...
   [480.4566   211.22343 ]
   [472.30084  211.23413 ]
   [  0.         0.      ]]

  [[483.19885   64.428154]
   [462.7715    80.66933 ]
   [462.7782    82.06549 ]
   ...
   [  0.         0.      ]
   [  0.         0.      ]

In [67]:
import numpy as np

def interpolate_keypoints(keypoints):
    interpolated_keypoints = keypoints.copy()
    num_frames, num_keypoints, _ = keypoints.shape
    
    for frame_idx in range(num_frames):
        for kp_idx in range(num_keypoints):
            if np.isnan(keypoints[frame_idx, kp_idx]).any():
                valid_neighbors = []
                for neighbor_idx in range(max(0, kp_idx - 1), min(num_keypoints, kp_idx + 2)):
                    if not np.isnan(keypoints[frame_idx, neighbor_idx]).any():
                        valid_neighbors.append(keypoints[frame_idx, neighbor_idx])
                
                if valid_neighbors:
                    interpolated_keypoints[frame_idx, kp_idx] = np.mean(valid_neighbors, axis=0)
    
    return interpolated_keypoints

# Example usage
keypoints = np.array([[[100, 20], [200, 0]], [[np.nan, np.nan], [300, 50]]])
interpolated_keypoints = interpolate_keypoints(keypoints)
print(interpolated_keypoints)


[[[100.  20.]
  [200.   0.]]

 [[300.  50.]
  [300.  50.]]]


In [105]:
# import numpy as np

# def generate_default_keypoints():
#     # Define default keypoints for each body part
#     default_keypoints = np.array([
#         [168.10754, 34.99607],  # Nose
#         [154.12099, 62.11058],  # Neck
#         [134.40283, 55.534725],  # Right Shoulder
#         [129.48523, 84.273926],  # Right Elbow
#         [163.97354, 86.75849],  # Right Wrist
#         [173.79732, 68.66142],  # Left Shoulder
#         [180.38019, 98.261826],  # Left Elbow
#         [194.3756, 104.81433],  # Left Wrist
#         [159.83676, 140.97232],  # Right Hip
#         [147.51527, 140.97325],  # Right Knee
#         [147.53452, 198.47025],  # Right Ankle
#         [146.72743, 258.40393],  # Left Hip
#         [171.35522, 140.98277],  # Left Knee
#         [171.36499, 194.38406],  # Left Ankle
#         [163.16327, 242.8349],  # Right Eye
#         [163.16515, 29.258884],  # Left Eye
#         [171.36163, 30.06396],  # Right Ear
#         [148.36261, 30.0791],  # Left Ear
#         [160.64582, 245.940548],  #Left big-toe
#         [176.27309, 249.39455],  #Left small-toe
#         [175.49535, 246.93071],  #Left heel
#         [160.64482, 246.940448],  #Right big-toe
#         [163.16066, 265.82828],  #Right small-toe
#         [157.39871, 266.68307],  #Right heel
#     ])
#     return default_keypoints

# def interpolate_keypoints(keypoints):
#     interpolated_keypoints = keypoints.copy()

#     num_frames = keypoints.shape[0]
#     num_keypoints = keypoints.shape[1]
    
#     default_keypoints = generate_default_keypoints()
    
#     for frame_idx in range(num_frames):
#         for kp_idx in range(num_keypoints):
#             if np.allclose(keypoints[frame_idx, kp_idx], [0, 0]):  # Check if keypoints are [0, 0] / if keypoint are not [0, 0] keep
#                 interpolated_keypoints[frame_idx, kp_idx] = default_keypoints[kp_idx]
    
#     return interpolated_keypoints

# # Example usage
# keypoints = np.load(r"E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\keypoints_extracted_clean\hugging\hugging_1.npy")

# interpolated_keypoints = interpolate_keypoints(keypoints)
# print(interpolated_keypoints)


import numpy as np

def generate_default_keypoints():
    # Define default keypoints for each body part
    default_keypoints = np.array([
        [168.10754, 34.99607],  # Nose
        [154.12099, 62.11058],  # Neck
        [134.40283, 55.534725],  # Right Shoulder
        [129.48523, 84.273926],  # Right Elbow
        [163.97354, 86.75849],  # Right Wrist
        [173.79732, 68.66142],  # Left Shoulder
        [180.38019, 98.261826],  # Left Elbow
        [194.3756, 104.81433],  # Left Wrist
        [159.83676, 140.97232],  # Right Hip
        [147.51527, 140.97325],  # Right Knee
        [147.53452, 198.47025],  # Right Ankle
        [146.72743, 258.40393],  # Left Hip
        [171.35522, 140.98277],  # Left Knee
        [171.36499, 194.38406],  # Left Ankle
        [163.16327, 242.8349],  # Right Eye
        [163.16515, 29.258884],  # Left Eye
        [171.36163, 30.06396],  # Right Ear
        [148.36261, 30.0791],  # Left Ear
        [160.64582, 245.940548],  #Left big-toe
        [176.27309, 249.39455],  #Left small-toe
        [175.49535, 246.93071],  #Left heel
        [160.64482, 246.940448],  #Right big-toe
        [163.16066, 265.82828],  #Right small-toe
        [157.39871, 266.68307],  #Right heel
    ])
    return default_keypoints

def interpolate_keypoints(keypoints):
    interpolated_keypoints = keypoints.copy()
    default_keypoints = generate_default_keypoints()
    
    for frame_idx in range(interpolated_keypoints.shape[0]):
        for kp_idx in range(interpolated_keypoints.shape[1]):
            for point_idx in range(interpolated_keypoints.shape[2]):
                if np.allclose(interpolated_keypoints[frame_idx, kp_idx, point_idx], [0, 0]):
                    interpolated_keypoints[frame_idx, kp_idx, point_idx] = default_keypoints[kp_idx]
    
    return interpolated_keypoints

# Load numpy file
keypoints = np.load(r"E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\keypoints_extracted_clean\hugging\hugging_5.npy")

# Interpolate keypoints
interpolated_keypoints = interpolate_keypoints(keypoints)
print(interpolated_keypoints)

[[[[409.76254 230.28624]
   [386.71805 256.07703]
   [397.4947  265.59494]
   [407.0539  299.67142]
   [439.65598 321.41446]
   [378.47205 247.93678]
   [168.10754  34.99607]
   [168.10754  34.99607]
   [386.65747 319.9886 ]
   [388.04944 321.40872]
   [386.6264  364.92233]
   [366.27786 401.5947 ]
   [381.22733 315.93643]
   [409.74344 354.00214]
   [407.06854 390.74188]
   [408.40945 223.52206]
   [168.10754  34.99607]
   [406.96298 227.56615]
   [385.21848 228.90549]
   [405.67236 394.81927]
   [405.66592 396.12958]
   [407.04593 396.11075]
   [385.26614 405.64633]
   [379.84637 407.0369 ]
   [362.1935  404.32132]]

  [[154.12099  62.11058]
   [428.73038 232.93713]
   [432.87466 223.44951]
   [154.12099  62.11058]
   [154.12099  62.11058]
   [424.73434 243.84085]
   [430.18808 287.37454]
   [431.50452 315.94144]
   [417.945   310.54153]
   [428.76688 309.1712 ]
   [154.12099  62.11058]
   [154.12099  62.11058]
   [413.82388 310.53253]
   [154.12099  62.11058]
   [154.12099  62.11058

In [106]:
np.save(r'E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\interpolate_data\hugging\hugging_5.npy', interpolated_keypoints)

interpolate all keypoint file

In [107]:
import os
import numpy as np

def generate_default_keypoints():
    # Define default keypoints for each body part
    default_keypoints = np.array([
        [168.10754, 34.99607],  # Nose
        [154.12099, 62.11058],  # Neck
        [134.40283, 55.534725],  # Right Shoulder
        [129.48523, 84.273926],  # Right Elbow
        [163.97354, 86.75849],  # Right Wrist
        [173.79732, 68.66142],  # Left Shoulder
        [180.38019, 98.261826],  # Left Elbow
        [194.3756, 104.81433],  # Left Wrist
        [159.83676, 140.97232],  # Right Hip
        [147.51527, 140.97325],  # Right Knee
        [147.53452, 198.47025],  # Right Ankle
        [146.72743, 258.40393],  # Left Hip
        [171.35522, 140.98277],  # Left Knee
        [171.36499, 194.38406],  # Left Ankle
        [163.16327, 242.8349],  # Right Eye
        [163.16515, 29.258884],  # Left Eye
        [171.36163, 30.06396],  # Right Ear
        [148.36261, 30.0791],  # Left Ear
        [160.64582, 245.940548],  #Left big-toe
        [176.27309, 249.39455],  #Left small-toe
        [175.49535, 246.93071],  #Left heel
        [160.64482, 246.940448],  #Right big-toe
        [163.16066, 265.82828],  #Right small-toe
        [157.39871, 266.68307],  #Right heel
    ])
    return default_keypoints

def interpolate_keypoints(keypoints):
    interpolated_keypoints = keypoints.copy()
    default_keypoints = generate_default_keypoints()
    
    for frame_idx in range(interpolated_keypoints.shape[0]):
        for kp_idx in range(interpolated_keypoints.shape[1]):
            for point_idx in range(interpolated_keypoints.shape[2]):
                if np.allclose(interpolated_keypoints[frame_idx, kp_idx, point_idx], [0, 0]):
                    interpolated_keypoints[frame_idx, kp_idx, point_idx] = default_keypoints[kp_idx]
    
    return interpolated_keypoints

# Define input and output folders
input_folder = r"E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\keypoints_extracted_clean"
output_folder = r"E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\interpolated_keypoints"

# Loop through subfolders
for subfolder in os.listdir(input_folder):
    subfolder_path = os.path.join(input_folder, subfolder)
    if os.path.isdir(subfolder_path):
        output_subfolder_path = os.path.join(output_folder, subfolder)
        os.makedirs(output_subfolder_path, exist_ok=True)
        # Loop through numpy files in subfolder
        for file_name in os.listdir(subfolder_path):
            if file_name.endswith(".npy"):
                # Load numpy file
                file_path = os.path.join(subfolder_path, file_name)
                keypoints = np.load(file_path)
                # Interpolate keypoints
                interpolated_keypoints = interpolate_keypoints(keypoints)
                # Save interpolated keypoints
                output_file_path = os.path.join(output_subfolder_path, file_name)
                np.save(output_file_path, interpolated_keypoints)
