In [9]:
import numpy as np

data = np.load(r"E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\30_frames_npy\kicking\kicking_1_0.npy")
print(data)

[[ 460.  563.]
 [ 419.  387.]
 [1017.  371.]
 [ 331.  307.]
 [ 643.  283.]
 [1098.  155.]
 [1003.  123.]
 [ 795.  116.]
 [ 244.  964.]
 [ 202.  732.]
 [ 444.  564.]
 [ 428.  458.]
 [1017.  380.]
 [ 643.  307.]
 [ 962.  228.]
 [1226.  180.]
 [1178.  172.]
 [ 770.  140.]
 [1002.  131.]
 [ 954.  123.]
 [ 179.  859.]
 [ 157.  755.]
 [ 426.  554.]
 [ 426.  452.]
 [ 339.  427.]
 [1010.  379.]
 [ 635.  306.]
 [ 947.  221.]
 [1226.  180.]
 [1177.  172.]
 [ 747.  148.]
 [ 995.  131.]
 [ 970.  123.]
 [ 196.  891.]
 [ 396.  564.]
 [ 739.  204.]
 [ 218.  922.]
 [ 740.  251.]
 [ 259.  957.]
 [ 474.  579.]
 [ 435.  459.]
 [1026.  388.]
 [ 651.  307.]
 [ 978.  236.]
 [1227.  180.]
 [1010.  132.]
 [ 787.  139.]
 [ 945.  123.]
 [ 274.  979.]
 [ 443.  483.]
 [ 627.  324.]
 [1226.  204.]
 [ 229. 1019.]
 [ 411.  500.]
 [ 627.  372.]
 [ 931.  316.]
 [ 762.  243.]
 [ 955.  173.]
 [ 395.  644.]
 [ 403.  531.]
 [ 763.  315.]
 [ 355.  684.]
 [ 395.  555.]
 [ 769.  387.]
 [ 763.  381.]
 [1163.  291.]
 [ 268.  9

In [42]:
data.shape

(78, 2)

In [31]:
data1=data[:, :-1]
print(data1)

[[ 442.]
 [1227.]
 [ 403.]
 [ 739.]
 [ 916.]
 [ 443.]
 [1050.]
 [ 643.]
 [1218.]
 [ 882.]
 [ 915.]
 [ 427.]
 [1042.]
 [ 634.]
 [ 699.]
 [1210.]
 [ 914.]
 [ 890.]
 [ 924.]
 [1202.]
 [ 938.]
 [1225.]
 [ 459.]
 [1051.]
 [ 651.]
 [1233.]
 [ 851.]
 [ 940.]
 [ 427.]
 [ 619.]
 [1226.]
 [ 811.]
 [ 962.]
 [1226.]
 [ 971.]
 [ 387.]
 [ 612.]
 [ 889.]
 [1195.]
 [ 899.]
 [ 874.]
 [1179.]
 [ 858.]
 [1106.]
 [1202.]
 [1169.]
 [ 404.]
 [ 628.]
 [ 850.]
 [1210.]
 [ 923.]
 [ 348.]
 [ 843.]
 [ 914.]
 [1187.]
 [ 362.]
 [ 836.]
 [1106.]
 [ 899.]
 [1202.]
 [1169.]
 [ 195.]
 [ 443.]
 [1226.]
 [ 387.]
 [ 732.]
 [ 914.]
 [ 451.]
 [ 410.]
 [ 746.]
 [ 923.]
 [1225.]
 [ 898.]
 [ 906.]
 [ 459.]
 [ 651.]
 [ 873.]
 [ 937.]]


In [10]:
np.save('modified_data.npy', data1)

In [6]:
import os
import numpy as np

main_folder = r'E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\30_frames_npy'
subfolders = ['hugging', 'kicking', 'none-interaction', 'pointing', 'pushing', 'punching']

def process_subfolder(subfolder):
    files = os.listdir(os.path.join(main_folder, subfolder))

    for file in files:
        file_path = os.path.join(main_folder, subfolder, file)
        data = np.load(file_path)
        
        data = data[:, :-1]
        np.save(file_path, data)

for subfolder in subfolders:
    process_subfolder(subfolder)

In [28]:
import os
import numpy as np

def preprocess_keypoints_folder(keypoints_folder, desired_num_keypoints):
    files = os.listdir(keypoints_folder)
    for file in files:
        filepath = os.path.join(keypoints_folder, file)
        data = np.load(filepath)
        num_keypoints = data.shape[0]
        if num_keypoints < desired_num_keypoints:
            # Pad with zeros
            padded_data = np.pad(data, ((0, desired_num_keypoints - num_keypoints), (0, 0)), mode='constant')
        elif num_keypoints > desired_num_keypoints:
            # Truncate
            padded_data = data[:desired_num_keypoints, :]
        else:
            padded_data = data
        np.save(filepath, padded_data)

# Define parameters
keypoints_folder = r"E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\30_frames_npy\pushing"
desired_num_keypoints = 36

# Preprocess keypoints folder
preprocess_keypoints_folder(keypoints_folder, desired_num_keypoints)


In [29]:
import numpy as np

# Load and print the preprocessed data
data = np.load(r"E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\30_frames_npy\pushing\pushing_1_1.npy")
print("Preprocessed data:")
print(data)
print("Shape:", data.shape)


Preprocessed data:
[[ 219.  748.]
 [ 443.  539.]
 [1227.  428.]
 [ 402.  404.]
 [ 331.  308.]
 [ 865.  108.]
 [ 458.  563.]
 [ 626.  347.]
 [1219.  172.]
 [ 955.  179.]
 [ 842.  139.]
 [ 427.  548.]
 [ 331.  476.]
 [ 937.  180.]
 [1217.  171.]
 [ 819.  140.]
 [ 915.  243.]
 [1226.  196.]
 [ 858.  179.]
 [ 898.  284.]
 [1226.  211.]
 [ 905.  195.]
 [ 490.  579.]
 [ 611.  347.]
 [1226.  173.]
 [ 979.  171.]
 [ 859.  133.]
 [ 578.  355.]
 [ 883.  163.]
 [ 962.  283.]
 [ 922.  178.]
 [ 921.  291.]
 [ 802.  228.]
 [1201.  212.]
 [ 347.  675.]
 [ 899.  355.]]
Shape: (36, 2)


test one data

In [61]:
import numpy as np

data_keypoint = np.load(r"E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\ch4_keypoints_numpy\hugging\hugging_1_1.npy")
print(data_keypoint)

[[ 442.  547.]
 [1227.  426.]
 [1050.  356.]
 [ 403.  340.]
 [ 915.   92.]
 [ 443.  563.]
 [1050.  365.]
 [ 643.  300.]
 [1218.  172.]
 [ 883.  164.]
 [ 914.  122.]
 [ 427.  541.]
 [1042.  364.]
 [ 634.  299.]
 [ 698.  236.]
 [1209.  171.]
 [ 915.  171.]
 [ 890.  116.]
 [ 937.  211.]
 [1202.  189.]
 [1219.  180.]
 [ 459.  580.]
 [1051.  371.]
 [ 651.  307.]
 [1227.  179.]
 [ 858.  156.]
 [ 939.  123.]
 [ 427.  628.]
 [1057.  387.]
 [ 619.  316.]
 [ 843.  204.]
 [1226.  196.]
 [ 956.  163.]
 [ 420.  643.]
 [ 626.  298.]
 [1226.  211.]
 [ 963.  188.]
 [ 387.  605.]
 [ 618.  355.]
 [ 890.  267.]
 [1195.  212.]
 [ 906.  189.]
 [ 874.  340.]
 [1179.  258.]
 [ 843.  419.]
 [1106.  348.]
 [1169.  292.]
 [ 404.  628.]
 [ 633.  371.]
 [ 851.  260.]
 [1210.  219.]
 [ 930.  189.]
 [ 379.  660.]
 [ 842.  339.]
 [1187.  259.]
 [ 362.  715.]
 [ 356.  684.]
 [ 835.  411.]
 [1106.  348.]
 [1202.  316.]
 [1169.  292.]
 [ 203.  652.]
 [ 443.  539.]
 [1226.  412.]
 [1050.  356.]
 [ 387.  339.]
 [ 913.   

In [62]:
data_keypoint.shape

(80, 2)

In [68]:
data_keypoint = np.random.rand(80, 2) 

In [69]:
print(data_keypoint)

[[0.69218601 0.95503963]
 [0.18919879 0.99477301]
 [0.65107005 0.0440569 ]
 [0.58754193 0.94101354]
 [0.76726746 0.37063252]
 [0.04004548 0.18073408]
 [0.90373909 0.77342176]
 [0.31691583 0.08128303]
 [0.44541208 0.71906457]
 [0.88912829 0.1247573 ]
 [0.35319652 0.69155646]
 [0.9630196  0.67933004]
 [0.09861244 0.57611207]
 [0.17667506 0.53566182]
 [0.55052188 0.22487707]
 [0.79663293 0.38802412]
 [0.71966762 0.30220505]
 [0.09234857 0.94024218]
 [0.73561029 0.44934403]
 [0.97839846 0.36856163]
 [0.1442526  0.14746407]
 [0.37737356 0.60639521]
 [0.62495518 0.25594981]
 [0.09837993 0.3193695 ]
 [0.10590214 0.43248427]
 [0.61903163 0.15136445]
 [0.31737704 0.18384826]
 [0.49995453 0.88616442]
 [0.21750327 0.08541611]
 [0.08333052 0.26567163]
 [0.15518607 0.21676525]
 [0.87780583 0.70641055]
 [0.85074277 0.53794278]
 [0.77344825 0.15603056]
 [0.52445197 0.88477669]
 [0.02983186 0.74589498]
 [0.0360347  0.10980268]
 [0.09980901 0.6739389 ]
 [0.88250829 0.62718499]
 [0.92376343 0.68001931]


In [70]:
num_additional_keypoints = 162000 - data_keypoint.shape[0]
additional_keypoints = np.random.rand(num_additional_keypoints, 2)

adjusted_keypoints = np.vstack((data_keypoint, additional_keypoints))

In [71]:
num_videos = 100
num_frames = 45
num_keypoints = 36
num_coordinates = 2

reshaped_data = adjusted_keypoints.reshape(num_videos, num_frames, num_keypoints, num_coordinates)


In [72]:
reshaped_data.shape

(100, 45, 36, 2)

In [92]:
data_keypoint1 = np.load(r"E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\ch4_keypoints_numpy\hugging\hugging_1_0.npy")
data_keypoint2 = np.load(r"E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\ch4_keypoints_numpy\punching\punching_1_0.npy")
data_keypoint3 = np.load(r"E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\ch4_keypoints_numpy\none-interaction\none_interaction_1_0.npy")

In [89]:
data_keypoint1.shape

(78, 2)

In [90]:
data_keypoint2.shape

(72, 2)

In [93]:
data_keypoint3.shape

(80, 2)

In [12]:
# import os
# import cv2

# def trim_video(input_path, output_path, target_duration=1.7):
#     # Open the video file
#     cap = cv2.VideoCapture(input_path)
#     # Check if the video file is opened successfully
#     if not cap.isOpened():
#         print(f"Error: Couldn't open {input_path}")
#         return

#     # Get total number of frames and frame rate
#     total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
#     fps = int(cap.get(cv2.CAP_PROP_FPS))

#     # Calculate target number of frames
#     target_frames = int(target_duration * fps)

#     # Calculate start and end frames for trimming
#     start_frame = (total_frames - target_frames) // 2
#     end_frame = start_frame + target_frames

#     # Set start frame
#     cap.set(cv2.CAP_PROP_POS_FRAMES, start_frame)

#     # Initialize video writer
#     fourcc = cv2.VideoWriter_fourcc(*'mp4v')
#     out = cv2.VideoWriter(output_path, fourcc, fps, (int(cap.get(cv2.CAP_PROP_FRAME_WIDTH)), int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))))

#     # Read and write frames for trimming
#     while start_frame < end_frame:
#         ret, frame = cap.read()
#         if ret:
#             out.write(frame)
#             start_frame += 1
#         else:
#             break

#     # Release video objects
#     cap.release()
#     out.release()

# root_folder = r"E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\test11222"
# # output_folder = r"E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\trim_video"
# output_folder = r"E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\test_more"
# classes = ['hugging', 'kicking', 'pointing', 'pushing', 'punching']

# for class_name in classes:
#     class_folder = os.path.join(root_folder, class_name)
#     output_class_folder = os.path.join(output_folder, class_name)
#     os.makedirs(output_class_folder, exist_ok=True)
#     for video_file in os.listdir(class_folder):
#         input_path = os.path.join(class_folder, video_file)
#         output_path = os.path.join(output_class_folder, video_file)
#         trim_video(input_path, output_path)
#         print(f"Trimmed {input_path} to {output_path}")



import os
import cv2

def trim_video(input_path, output_path, target_duration=1.7):
    # Open the video file
    cap = cv2.VideoCapture(input_path)
    # Check if the video file is opened successfully
    if not cap.isOpened():
        print(f"Error: Couldn't open {input_path}")
        return

    # Get total number of frames and frame rate
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    fps = int(cap.get(cv2.CAP_PROP_FPS))

    # Calculate target number of frames
    target_frames = int(target_duration * fps)

    # Calculate start and end frames for trimming
    start_frame = (total_frames - target_frames) // 2
    end_frame = start_frame + target_frames

    # Set start frame
    cap.set(cv2.CAP_PROP_POS_FRAMES, start_frame)

    # Initialize video writer
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    out = cv2.VideoWriter(output_path, fourcc, fps, (int(cap.get(cv2.CAP_PROP_FRAME_WIDTH)), int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))))

    # Read and write frames for trimming
    while start_frame < end_frame:
        ret, frame = cap.read()
        if ret:
            out.write(frame)
            start_frame += 1
        else:
            break

    # Release video objects
    cap.release()
    out.release()

root_folder = r"E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\tuk-add"
output_folder = r"E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\final-dataset-video"
classes = ['hugging', 'kicking', 'pointing', 'pushing', 'none-interaction']

for class_name in classes:
    class_folder = os.path.join(root_folder, class_name)
    output_class_folder = os.path.join(output_folder, class_name)
    os.makedirs(output_class_folder, exist_ok=True)
    for video_file in os.listdir(class_folder):
        input_path = os.path.join(class_folder, video_file)
        output_path = os.path.join(output_class_folder, video_file)
        trim_video(input_path, output_path)
        print(f"Trimmed {input_path} to {output_path}")



Trimmed E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\tuk-add\hugging\hugging_1.mp4 to E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\final-dataset-video\hugging\hugging_1.mp4
Trimmed E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\tuk-add\hugging\hugging_10.mp4 to E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\final-dataset-video\hugging\hugging_10.mp4
Trimmed E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\tuk-add\hugging\hugging_100.mp4 to E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\final-dataset-video\hugging\hugging_100.mp4
Trimmed E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\tuk-add\hugging\hugging_101.mp4 to E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\final-dataset-video\hugging\hugging_101.mp4
Trimmed E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\tuk-add\hugging\hugging_102.m

In [13]:
import os
import cv2

def get_video_duration(video_path):
    # Open the video file
    cap = cv2.VideoCapture(video_path)
    # Check if the video file is opened successfully
    if not cap.isOpened():
        print(f"Error: Couldn't open {video_path}")
        return None
    # Get the duration of the video
    duration = int(cap.get(cv2.CAP_PROP_FRAME_COUNT)) / int(cap.get(cv2.CAP_PROP_FPS))
    cap.release()
    return duration

root_folder = r"E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\final-dataset-video"
classes = ['hugging', 'kicking', 'pointing', 'pushing', 'none-interaction']

for class_name in classes:
    class_folder = os.path.join(root_folder, class_name)
    print(f"Class: {class_name}")
    for video_file in os.listdir(class_folder):
        video_path = os.path.join(class_folder, video_file)
        duration = get_video_duration(video_path)
        if duration is not None:
            print(f"Video: {video_file}, Duration: {duration} seconds")


Class: hugging
Video: hugging_1.mp4, Duration: 1.7 seconds
Video: hugging_10.mp4, Duration: 1.7 seconds
Video: hugging_100.mp4, Duration: 1.7 seconds
Video: hugging_101.mp4, Duration: 1.7 seconds
Video: hugging_102.mp4, Duration: 1.7 seconds
Video: hugging_103.mp4, Duration: 1.7 seconds
Video: hugging_104.mp4, Duration: 1.7 seconds
Video: hugging_105.mp4, Duration: 1.7 seconds
Video: hugging_106.mp4, Duration: 1.7 seconds
Video: hugging_107.mp4, Duration: 1.7 seconds
Video: hugging_108.mp4, Duration: 1.7 seconds
Video: hugging_109.mp4, Duration: 1.7 seconds
Video: hugging_11.mp4, Duration: 1.7 seconds
Video: hugging_110.mp4, Duration: 1.7 seconds
Video: hugging_111.mp4, Duration: 1.7 seconds
Video: hugging_112.mp4, Duration: 1.7 seconds
Video: hugging_113.mp4, Duration: 1.7 seconds
Video: hugging_114.mp4, Duration: 1.7 seconds
Video: hugging_115.mp4, Duration: 1.7 seconds
Video: hugging_116.mp4, Duration: 1.7 seconds
Video: hugging_117.mp4, Duration: 1.7 seconds
Video: hugging_118.mp4,

check frame total

In [14]:
import os
import cv2

def get_video_frame_count(video_path):
    # Open the video file
    cap = cv2.VideoCapture(video_path)
    # Check if the video file is opened successfully
    if not cap.isOpened():
        print(f"Error: Couldn't open {video_path}")
        return None
    # Get the total number of frames in the video
    frame_count = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    cap.release()
    return frame_count

root_folder = r"E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\final-dataset-video"
classes = ['hugging', 'kicking', 'pointing', 'pushing', 'none-interaction']

for class_name in classes:
    class_folder = os.path.join(root_folder, class_name)
    print(f"Class: {class_name}")
    total_frames = 0
    for video_file in os.listdir(class_folder):
        video_path = os.path.join(class_folder, video_file)
        frame_count = get_video_frame_count(video_path)
        if frame_count is not None:
            total_frames += frame_count
            print(f"Video: {video_file}, Frame Count: {frame_count}")
    print(f"Total Frames in {class_name}: {total_frames}")


Class: hugging
Video: hugging_1.mp4, Frame Count: 51
Video: hugging_10.mp4, Frame Count: 51
Video: hugging_100.mp4, Frame Count: 51
Video: hugging_101.mp4, Frame Count: 51
Video: hugging_102.mp4, Frame Count: 51
Video: hugging_103.mp4, Frame Count: 51
Video: hugging_104.mp4, Frame Count: 51
Video: hugging_105.mp4, Frame Count: 51
Video: hugging_106.mp4, Frame Count: 51
Video: hugging_107.mp4, Frame Count: 51
Video: hugging_108.mp4, Frame Count: 51
Video: hugging_109.mp4, Frame Count: 51
Video: hugging_11.mp4, Frame Count: 51
Video: hugging_110.mp4, Frame Count: 51
Video: hugging_111.mp4, Frame Count: 51
Video: hugging_112.mp4, Frame Count: 51
Video: hugging_113.mp4, Frame Count: 51
Video: hugging_114.mp4, Frame Count: 51
Video: hugging_115.mp4, Frame Count: 51
Video: hugging_116.mp4, Frame Count: 51
Video: hugging_117.mp4, Frame Count: 51
Video: hugging_118.mp4, Frame Count: 51
Video: hugging_119.mp4, Frame Count: 51
Video: hugging_12.mp4, Frame Count: 51
Video: hugging_120.mp4, Frame 

trim old video

In [4]:
import os
import cv2

def trim_video(input_path, output_path, target_duration=1.7):
    # Open the video file
    cap = cv2.VideoCapture(input_path)
    # Check if the video file is opened successfully
    if not cap.isOpened():
        print(f"Error: Couldn't open {input_path}")
        return

    # Get total number of frames and frame rate
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    fps = int(cap.get(cv2.CAP_PROP_FPS))

    # Calculate target number of frames
    target_frames = int(target_duration * fps)

    # Calculate start and end frames for trimming
    start_frame = (total_frames - target_frames) // 2
    end_frame = start_frame + target_frames

    # Set start frame
    cap.set(cv2.CAP_PROP_POS_FRAMES, start_frame)

    # Initialize video writer
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    out = cv2.VideoWriter(output_path, fourcc, fps, (int(cap.get(cv2.CAP_PROP_FRAME_WIDTH)), int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))))

    # Read and write frames for trimming
    while start_frame < end_frame:
        ret, frame = cap.read()
        if ret:
            out.write(frame)
            start_frame += 1
        else:
            break

    # Release video objects
    cap.release()
    out.release()

root_folder = r"E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\add_more_data"
output_folder = r"E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\trim_add_more_data"
classes = ['hugging', 'kicking', 'pointing', 'pushing', 'punching', 'none-interaction']

for class_name in classes:
    class_folder = os.path.join(root_folder, class_name)
    output_class_folder = os.path.join(output_folder, class_name)
    os.makedirs(output_class_folder, exist_ok=True)
    for video_file in os.listdir(class_folder):
        input_path = os.path.join(class_folder, video_file)
        output_path = os.path.join(output_class_folder, video_file)
        trim_video(input_path, output_path)
        print(f"Trimmed {input_path} to {output_path}")


Trimmed E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\add_more_data\hugging\hugging_101.mp4 to E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\trim_add_more_data\hugging\hugging_101.mp4
Trimmed E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\add_more_data\hugging\hugging_102.mp4 to E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\trim_add_more_data\hugging\hugging_102.mp4
Trimmed E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\add_more_data\hugging\hugging_103.mp4 to E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\trim_add_more_data\hugging\hugging_103.mp4
Trimmed E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\add_more_data\hugging\hugging_104.mp4 to E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\trim_add_more_data\hugging\hugging_104.mp4
Trimmed E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\add

In [5]:
import os
import cv2

def get_video_duration(video_path):
    # Open the video file
    cap = cv2.VideoCapture(video_path)
    # Check if the video file is opened successfully
    if not cap.isOpened():
        print(f"Error: Couldn't open {video_path}")
        return None
    # Get the duration of the video
    duration = int(cap.get(cv2.CAP_PROP_FRAME_COUNT)) / int(cap.get(cv2.CAP_PROP_FPS))
    cap.release()
    return duration

root_folder = r"E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\trim_add_more_data"
classes = ['hugging', 'kicking', 'pointing', 'pushing', 'punching', 'none-interaction']

for class_name in classes:
    class_folder = os.path.join(root_folder, class_name)
    print(f"Class: {class_name}")
    for video_file in os.listdir(class_folder):
        video_path = os.path.join(class_folder, video_file)
        duration = get_video_duration(video_path)
        if duration is not None:
            print(f"Video: {video_file}, Duration: {duration} seconds")

Class: hugging
Video: hugging_101.mp4, Duration: 1.7 seconds
Video: hugging_102.mp4, Duration: 1.7 seconds
Video: hugging_103.mp4, Duration: 1.7 seconds
Video: hugging_104.mp4, Duration: 1.7 seconds
Video: hugging_105.mp4, Duration: 1.7 seconds
Video: hugging_106.mp4, Duration: 1.7 seconds
Video: hugging_107.mp4, Duration: 1.7 seconds
Video: hugging_108.mp4, Duration: 1.7 seconds
Video: hugging_109.mp4, Duration: 1.7 seconds
Video: hugging_110.mp4, Duration: 1.7 seconds
Video: hugging_111.mp4, Duration: 1.7 seconds
Video: hugging_112.mp4, Duration: 1.7 seconds
Video: hugging_113.mp4, Duration: 1.7 seconds
Video: hugging_114.mp4, Duration: 1.7 seconds
Video: hugging_115.mp4, Duration: 1.7 seconds
Class: kicking
Video: kicking_101.mp4, Duration: 1.7 seconds
Video: kicking_102.mp4, Duration: 1.7 seconds
Video: kicking_103.mp4, Duration: 1.7 seconds
Video: kicking_104.mp4, Duration: 1.7 seconds
Video: kicking_105.mp4, Duration: 1.7 seconds
Video: kicking_106.mp4, Duration: 1.7 seconds
Vide

In [43]:
import os
import numpy as np
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv3D, MaxPooling3D, LSTM, Dense, Flatten

def load_keypoints_data(root_folder, classes, num_videos_per_class, max_num_frames, num_keypoints):
    input_tensor = []
    labels = []
    class_idx = 0

    for class_name in classes:
        class_folder = os.path.join(root_folder, class_name)
        files = os.listdir(class_folder)
        videos_sampled = np.random.choice(files, num_videos_per_class, replace=False)

        for video_file in videos_sampled:
            # Load keypoints from .npy files
            keypoints = np.load(os.path.join(class_folder, video_file))

            # Pad or truncate keypoints data to ensure consistent length
            num_frames = min(max_num_frames, keypoints.shape[0])
            keypoints = keypoints[:num_frames, :num_keypoints]

            # Append keypoints and label to lists
            input_tensor.append(keypoints)
            labels.append(class_idx)

        class_idx += 1

    return np.array(input_tensor), np.array(labels)

# Parameters
root_folder = r"E:\Drive D\MA-ICT Convergence\Thesis\Human-Human-Interaction\dataset\30_frames_npy"
classes = ['hugging', 'kicking', 'none-interaction', 'pushing', 'punching', 'pointing']
num_videos_per_class = 100
max_num_frames = 30
num_keypoints = 36
num_classes = len(classes)

# Load keypoints data
input_tensor, labels = load_keypoints_data(root_folder, classes, num_videos_per_class, max_num_frames, num_keypoints)

# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(input_tensor, labels, test_size=0.2, random_state=42)

# Reshape input for 3D CNN (add channel dimension)
X_train = np.expand_dims(X_train, axis=-1)
X_test = np.expand_dims(X_test, axis=-1)


num_frames = 30
num_keypoints = 36
num_dimensions = 2
num_classes = 6

(600, 30, 2)